language: python
python: 2.7
env:
  - TARGET=tests
  - TARGET=quality-assurance
before_install:
  - pip install -U distribute
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: make install
script: make $TARGET
